name: Check Lua Formatting

on:
  pull_request:
  push:
    branches: [main]

jobs:
  stylua-check:
    name: Stylua Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stylua Check
        uses: JohnnyMorganz/stylua-action@v3
        with:
          version: latest
          args: --check .
